/*
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WhereItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-18T16:08:28.307Z")
public class WhereItem {
  @SerializedName("type")
  private String type = null;

  @SerializedName("column")
  private String column = null;

  @SerializedName("value")
  private String value = null;

  public WhereItem type(String type) {
    this.type = type;
    return this;
  }

   /**
   * You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public WhereItem column(String column) {
    this.column = column;
    return this;
  }

   /**
   * Column name
   * @return column
  **/
  @ApiModelProperty(example = "null", value = "Column name")
  public String getColumn() {
    return column;
  }

  public void setColumn(String column) {
    this.column = column;
  }

  public WhereItem value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Column value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "Column value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhereItem whereItem = (WhereItem) o;
    return Objects.equals(this.type, whereItem.type) &&
        Objects.equals(this.column, whereItem.column) &&
        Objects.equals(this.value, whereItem.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, column, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhereItem {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

